spring:
  application:
    name: auth-example
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

dew:
  cluster:
    cache: redis
  security:
    token-flag: _token_
    token-in-header: true
    token-hash: false

