spring:
  application:
    name: oss-example

server:
  port: 8081

dew:
  oss1:
    ossType: oss
    accessKeyId: LTAI5tH8SerhbcVTKRRPajib
    accessKeyIdSecret: mkjVVKiz9KMvKJvo6Eg5ojfph2M7oH
    endpoint: oss-cn-beijing.aliyuncs.com
    securityToken: default
  oss:
    ossType: obs
    endpoint: obs.cn-east-3.myhuaweicloud.com
    accessKeyId: STMOYGVHG61WTTN3AWDB
    accessKeyIdSecret: kvSsUD7eJD4ltUH8HTjwloHhVWo5A2uVmZqzUzUN
    securityToken: default
  oss2:
    ossType: minio
    endpoint: http://172.30.86.196:9000
    accessKeyId: P8RXPMSR5T1YLTX6NZLO
    accessKeyIdSecret: SLQL62TZHPtJxKUu1Mbz6rOgebuov9KtQhbHZUbD
    securityToken: default
  oss4:
    ossType: minio
    endpoint: https://play.min.io
    accessKeyId: Q3AM3UQ867SPQQA43P2F
    accessKeyIdSecret: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
    securityToken: default



