spring:
  application:
    name: web-example

server:
  port: 809 # http端口号
#  servlet:
#    context-path: /tt

dew:
  basic:
    name: web示例
    version: 1.0
    desc: 这是一个Web示例
    web-site: http://www.idealworld.group
    doc:
      base-package: group.idealworld.dew # API文档路径
  security:
    ident-info-enabled: false

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: '*'
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
